### ISSUE TITLE
Tempature/Pressure calibrations wrong?

### ISSUE THREAD

**Issue by Marsfan** [adafruit/Adafruit_BMP085_Unified#11]
When I look at the BMP085 datasheet, it says that I need to take the values of registers 0xAA and 0xAB and merge the two together, but looking at this code (and at sparkfun's) they both only use 0xAA.
This happens with all of the values, why is this?

**Comment by microbuilder** [comment]
The driver reads two bytes (16-bit value) starting at 0xAA, and the second byte will automatically be the next value which is 0xAB, etc.
