### ISSUE TITLE
Changing pins?

### ISSUE THREAD

**Issue by wouterk1** [adafruit/Adafruit_BMP085_Unified#20]
Hey all

A little question. I am using this for a project but I need to use other pins. i am using pin 5 and 6. How can I change this pins becouse i can't find any pin declaration.

Greets Wouter

**Comment by microbuilder** [comment]
Please post support questions up in the Adafruit support forums, thanks.  Github is only for monitoring pull requests and support doesn't get the emails from here.  Thanks!
