### ISSUE TITLE
The .github folder causes a compile warning on Windows

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [adafruit/Adafruit_BMP085_Unified#21]
The .github folder causes a compile warning on Windows

WARNING: Spurious .github folder in 'Adafruit BMP085 Unified' library

**Comment by ladyada** [comment]
wontfix - we need that to create issue templates. hopefully arduino will fix at some point :)

**Comment by rogerclarkmelbourne** [comment]
OK. No worries.

Perhaps I should post an issue on the Arduino.cc github repo asking them to ignore any files starting with "."

**Comment by per1234** [comment]
> we need that to create issue templates

@ladyada the .github folder is not necessary for issue templates(see https://help.github.com/articles/creating-an-issue-template-for-your-repository). As I recommended in https://github.com/adafruit/RGB-matrix-Panel/issues/26, you could put the templates in the repository root instead. Even if Arduino removes the warning, this will still be a problem until the fixed version of the IDE is released and the users upgrade to it.

> Perhaps I should post an issue on the Arduino.cc github repo asking them to ignore any files starting with "."

@rogerclarkmelbourne this was already requested in https://github.com/arduino/arduino-builder/issues/70#issuecomment-158994311. The response indicated that, at least at that time, the developer was unwilling to make the warning ignore all folders starting with "." but requesting .github be ignored might have a chance.

**Comment by ladyada** [comment]
oh ok we might try moving it to the root dir, i think we missed that it didnt have to go into .github - no ETA on when we may do the sweep (there's 200 repos :)
